### ISSUE TITLE
Doesn't seem to work but no errors. Am I doing something wrong?

### ISSUE THREAD

**Issue by crhistianramirez** [hiraldesai/AzureTableStorageConfigurationProvider#3]
I'm not very experienced with c# but I think it should work. Am I doing something wrong? I don't see any errors but my models are null and if I set a breakpoint and try to inspect my table values I don't see anything. 

Is there something I can do to help debug?

```csharp
public class AppSettings: IAppSettings
{
    public string AcmeAccountKey { get; set; }
}
```

```csharp
.ConfigureAppConfiguration((context, config) =>
{
    var tableStorageBuilder = new ConfigurationBuilder();
    var storageConnectionString = Environment.GetEnvironmentVariable("AzureStorageConnection");
    if (string.IsNullOrEmpty(storageConnectionString))
        throw new Exception("Environment variable AzureStorageConnection must be defined in order to load AppSettings");
    tableStorageBuilder.AddAzureTableStorage(storageConnectionString, "appsettings", "appsettings");
    var tableStorageConfig = tableStorageBuilder.Build();
    config.AddConfiguration(tableStorageConfig);

    var settings = tableStorageConfig.Get<AppSettings>(); // all values for settings are null

});
```

![Screenshot_1](https://user-images.githubusercontent.com/16483662/81107031-2270f980-8edc-11ea-8393-2b36c136a212.png)

**Comment by crhistianramirez** [comment]
Ahhh, complete facepalm. I thought it was picking up the values for a single row, which as I see now doesn't even make sense because I never specified a row value in the config. I now see that each row is ultimately transformed into a value. 

Neat library, works fine but I think it could be a lot simpler by focusing on a single row. Then you just add a new column to the row and you can easily compare against other sets of configurations. For example compare test settings to production settings

**Comment by hiraldesai** [comment]
Hi @crhistianramirez - thank you for using this library. Sorry you faced the issue earlier. The reason I kept one row per config was because I wanted to keep it a little more scalable for apps with many key value pairs. It made more sense for the application I was working on at the time I built this. Thanks for the feedback though.
